version: '3.8'
services:
  postgres:
    container_name: sber_test-postgres
    image:  postgres:15.1-alpine
    restart: always
    ports:
      - 5431:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USERNAME}"]
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  postgres_data:
    name: sber_test-postgres