services:
  api:
    container_name: sber_test-api
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: sber_test-postgres
    image:  postgres:15.1-alpine
    volumes:
      - type: bind
        source: /var/lib/postgresql/data
        target: /var/lib/postgresql/data
        bind:
          create_host_path: true
    ports:
      - ${POSTGRES_PORT}:5432
    env_file: .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USERNAME}"]
      interval: 5s
      timeout: 3s
      retries: 3